// This file is only for testing purposes

GET http://localhost:3000/auth/allusers

###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "andy",
    "password": "very_sceret",
    "name": "Andy Droid",
    "userType": "student"
}

###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "sovit",
    "password": "The_Strong_Password",
    "name": "Sovit Kumar",
    "userType": "alumni"
}


###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "aadil",
    "password": "yes this is the password",
    "name": "Aadil M",
    "userType": "admin"
}

###

GET http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "aadil",
    "password": "yes this is the password"
}

###

GET http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "aadil",
    "password": "The wrong password"
}

###

GET http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "google",
    "password": "The account is non existance"
}

